name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # optional light tooling
          pip install flake8

      - name: Lint (flake8)
        run: flake8 --max-line-length=100 --extend-ignore=E203 .

      - name: Smoke test (import + render)
        run: |
          python - <<'PY'
          import main
          from main import app
          with app.test_client() as c:
              r = c.get('/')
              assert r.status_code == 200, "Home route should load"
          print("Smoke test OK")
          PY
